"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const schema_validator_1 = require("../middlewares/schema-validator");
const express_1 = require("express");
const petshop_schema_1 = require("../schemas/petshop-schema");
const petshop_controller_1 = require("../controllers/petshop-controller");
const petshopRouter = (0, express_1.Router)();
petshopRouter.post("/", (0, schema_validator_1.validateSchemaMiddleware)(petshop_schema_1.createPetshopSchema), petshop_controller_1.createPetshop);
petshopRouter.post("/check", (0, schema_validator_1.validateSchemaMiddleware)(petshop_schema_1.bestPetshoptSchema), petshop_controller_1.checkBestPetshop);
petshopRouter.get("/", petshop_controller_1.getAllPetshops);
exports.default = petshopRouter;
